import GraphQLProvider from "@/components/graphql/GraphQLProvider.";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GraphQLProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </GraphQLProvider>
      </body>
    </html>
  );
}
